import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shawii',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async></script>

    <body className={inter.className}>{children}</body>
 
    </html>
  )
}
